package ViewLuidgi;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author luidgivarela
 */
import ModelLuidgi.BancoUsuarios;
import ModelLuidgi.Cliente;
import ModelLuidgi.Usuario;
import ModelLuidgi.SessaoUsuario;
import ModelLuidgi.UsuarioLogado;
import javax.swing.JOptionPane;
import javax.swing.text.MaskFormatter;
import javax.swing.JFormattedTextField;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import java.util.List;


public class ConsultaPerfilCliente_back extends javax.swing.JFrame implements UsuarioLogado{
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ConsultaPerfilCliente_back.class.getName());

    /**
     * Creates new form ConsultaPerfil_back
     */
    private Usuario cliente;
    
    public ConsultaPerfilCliente_back(Usuario cliente) {
        this.cliente = cliente;
        initComponents();
        preencherDados();
        setUsuarioLogado(cliente);
        setSize(900, 800);
        setLocationRelativeTo(null);
    }

    @Override
    public void setUsuarioLogado(Usuario cliente) {
        String nomeCompleto = cliente.getNome();
        String nomeCurto = nomeCompleto.length() > 18 ? nomeCompleto.substring(0, 18) + "..." : nomeCompleto;

        labelUsuarioLogado.setText("Usuário: " + nomeCurto);
        labelUsuarioLogado.setToolTipText("Usuário: " + nomeCompleto);
    }

    @Override
    public Usuario getUsuarioLogado() {
        return this.cliente;
    }
    
    private void preencherDados() {
        Cliente c = (Cliente) cliente;

        labelNomeValor.setText(c.getNome());
        campoEmail.setText(c.getEmail());
        campoTelefone1.setText(c.getTelefone());
        campoCEP.setText(c.getCep());
        campoNumResidencia.setText(c.getNumero());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jButton7 = new javax.swing.JButton();
        labelTelefone = new javax.swing.JLabel();
        labelEmail = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        labelUsuarioLogado = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jButton8 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        labelTelefone1 = new javax.swing.JLabel();
        labelEmail1 = new javax.swing.JLabel();
        labelCEP = new javax.swing.JLabel();
        labelNumResidencia = new javax.swing.JLabel();
        labelNomeValor = new javax.swing.JLabel();
        campoTelefone1 = new javax.swing.JLabel();
        campoEmail = new javax.swing.JLabel();
        campoCEP = new javax.swing.JLabel();
        campoNumResidencia = new javax.swing.JLabel();
        botaoEditarNome = new javax.swing.JButton();
        botaoEditarTelefone = new javax.swing.JButton();
        botaoEditarCEP = new javax.swing.JButton();
        botaoEditarEmail = new javax.swing.JButton();
        botaoEditarNumResidencia = new javax.swing.JButton();

        jButton7.setBackground(new java.awt.Color(255, 193, 7));
        jButton7.setText("✅Salvar aterações");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        labelTelefone.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        labelTelefone.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTelefone.setText("📞 Seu telefone:");

        labelEmail.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        labelEmail.setText("📧 Seu email:");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(123, 63, 0));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jButton1.setBackground(new java.awt.Color(255, 193, 7));
        jButton1.setText("🍕 Início");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(255, 193, 7));
        jButton3.setText("👋 Sair");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(255, 193, 7));
        jButton6.setText("👤Consulte seu Perfil");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton12.setBackground(new java.awt.Color(255, 193, 7));
        jButton12.setText("🕓Consulte seu Histórico");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        labelUsuarioLogado.setBackground(new java.awt.Color(255, 193, 7));
        labelUsuarioLogado.setText("Usuário:");
        labelUsuarioLogado.setOpaque(true);
        labelUsuarioLogado.setPreferredSize(new java.awt.Dimension(156, 23));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton12)
                .addGap(18, 18, 18)
                .addComponent(jButton6)
                .addGap(18, 18, 18)
                .addComponent(labelUsuarioLogado, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton3)
                    .addComponent(jButton6)
                    .addComponent(jButton12)
                    .addComponent(labelUsuarioLogado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(11, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 248, 220));

        jLabel1.setFont(new java.awt.Font("Herculanum", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Dados do seu perfil");

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new java.awt.GridBagLayout());

        jButton8.setBackground(new java.awt.Color(255, 193, 7));
        jButton8.setText("✅Salvar aterações");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(49, 38, 0, 161);
        jPanel4.add(jButton8, gridBagConstraints);

        jLabel2.setText("👤Seu nome:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(16, 347, 0, 0);
        jPanel4.add(jLabel2, gridBagConstraints);

        labelTelefone1.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        labelTelefone1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTelefone1.setText("📞 Seu telefone:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 315, 0, 0);
        jPanel4.add(labelTelefone1, gridBagConstraints);

        labelEmail1.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        labelEmail1.setText("📧 Seu email:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 335, 0, 0);
        jPanel4.add(labelEmail1, gridBagConstraints);

        labelCEP.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        labelCEP.setText("📮 Seu CEP:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.ipadx = -5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 346, 0, 0);
        jPanel4.add(labelCEP, gridBagConstraints);

        labelNumResidencia.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        labelNumResidencia.setText("🏠 Número de sua residência:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.ipadx = -5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(27, 235, 0, 0);
        jPanel4.add(labelNumResidencia, gridBagConstraints);

        labelNomeValor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(123, 63, 0), 3));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 194;
        gridBagConstraints.ipady = 17;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 18, 0, 0);
        jPanel4.add(labelNomeValor, gridBagConstraints);

        campoTelefone1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(123, 63, 0), 3));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.ipadx = 194;
        gridBagConstraints.ipady = 17;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 18, 0, 0);
        jPanel4.add(campoTelefone1, gridBagConstraints);

        campoEmail.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(123, 63, 0), 3));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 194;
        gridBagConstraints.ipady = 17;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 18, 0, 0);
        jPanel4.add(campoEmail, gridBagConstraints);

        campoCEP.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(123, 63, 0), 3));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 194;
        gridBagConstraints.ipady = 17;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 18, 0, 0);
        jPanel4.add(campoCEP, gridBagConstraints);

        campoNumResidencia.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(123, 63, 0), 3));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 194;
        gridBagConstraints.ipady = 17;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(27, 18, 0, 0);
        jPanel4.add(campoNumResidencia, gridBagConstraints);

        botaoEditarNome.setBackground(new java.awt.Color(255, 193, 7));
        botaoEditarNome.setText("🛠️ Editar");
        botaoEditarNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoEditarNomeActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipady = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(14, 12, 0, 0);
        jPanel4.add(botaoEditarNome, gridBagConstraints);

        botaoEditarTelefone.setBackground(new java.awt.Color(255, 193, 7));
        botaoEditarTelefone.setText("🛠️ Editar");
        botaoEditarTelefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoEditarTelefoneActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 12, 0, 0);
        jPanel4.add(botaoEditarTelefone, gridBagConstraints);

        botaoEditarCEP.setBackground(new java.awt.Color(255, 193, 7));
        botaoEditarCEP.setText("🛠️ Editar");
        botaoEditarCEP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoEditarCEPActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 12, 0, 0);
        jPanel4.add(botaoEditarCEP, gridBagConstraints);

        botaoEditarEmail.setBackground(new java.awt.Color(255, 193, 7));
        botaoEditarEmail.setText("🛠️ Editar");
        botaoEditarEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoEditarEmailActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 12, 0, 0);
        jPanel4.add(botaoEditarEmail, gridBagConstraints);

        botaoEditarNumResidencia.setBackground(new java.awt.Color(255, 193, 7));
        botaoEditarNumResidencia.setText("🛠️ Editar");
        botaoEditarNumResidencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoEditarNumResidenciaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(27, 12, 0, 0);
        jPanel4.add(botaoEditarNumResidencia, gridBagConstraints);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(457, 457, 457)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(393, 393, 393))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addComponent(jLabel1)
                .addGap(6, 6, 6)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(357, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        LoginCliente_back telaLogin = new LoginCliente_back();
        telaLogin.setVisible(true);
        this.dispose(); // Fecha a tela atual
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        Usuario u = BancoUsuarios.listaUsuarios.get(0);

        if (u instanceof Cliente) {
            Cliente clienteLogado = (Cliente) u;
            ConsultaPerfilCliente_back telaPerfil = new ConsultaPerfilCliente_back(clienteLogado);
            telaPerfil.setVisible(true);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(null, "O usuário logado não é um cliente.");
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        Usuario u = BancoUsuarios.getListaUsuarios().get(0);
        Cliente clienteLogado = null;

        if (u instanceof Cliente) {
            clienteLogado = (Cliente) u;

            ConsultaHistorico telaHistorico = new ConsultaHistorico(clienteLogado);
            telaHistorico.setVisible(true);
            this.dispose(); // Fecha a janela atual
        } else {
            JOptionPane.showMessageDialog(null, "O usuário logado não é um cliente.");
        }
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        JOptionPane.showMessageDialog(this, "✔️ Alterações registradas!");
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        JOptionPane.showMessageDialog(this, "✔️ Alterações registradas!");
        
        Usuario u = BancoUsuarios.listaUsuarios.get(0);

        if (u instanceof Cliente) {
            Cliente clienteLogado = (Cliente) u;
            ConsultaPerfilCliente_back telaPerfil = new ConsultaPerfilCliente_back(clienteLogado);
            telaPerfil.setVisible(true);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(null, "O usuário logado não é um cliente.");
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void botaoEditarNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoEditarNomeActionPerformed
    try {
        // Máscara para telefone: (##) #####-####
        MaskFormatter maskTelefone = new MaskFormatter("(##) #####-####");
        maskTelefone.setPlaceholderCharacter('_');

        JFormattedTextField campoNovoTelefone = new JFormattedTextField(maskTelefone);

        Cliente cliente = (Cliente) this.cliente;

        // Preenche o valor atual do telefone
        campoNovoTelefone.setValue(cliente.getTelefone());

        int opcao = JOptionPane.showConfirmDialog(
            this,
            campoNovoTelefone,
            "Digite o novo telefone:",
            JOptionPane.OK_CANCEL_OPTION,
            JOptionPane.PLAIN_MESSAGE
        );

        if (opcao == JOptionPane.OK_OPTION) {
            String novoTelefone = campoNovoTelefone.getText();

            if (novoTelefone.contains("_")) {
                JOptionPane.showMessageDialog(this, "Telefone incompleto.");
            } else {
                cliente.setTelefone(novoTelefone);
                campoTelefone1.setText(novoTelefone); // <- o campo visual na tela
            }
        }
    } catch (ParseException e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Erro ao formatar o telefone.");
    }
    }//GEN-LAST:event_botaoEditarNomeActionPerformed

    private void botaoEditarEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoEditarEmailActionPerformed
        try {
            // Cria uma máscara para o campo do JOptionPane
            MaskFormatter maskCEP = new MaskFormatter("#####-###");
            maskCEP.setPlaceholderCharacter('_');

            // Campo formatado que será exibido no JOptionPane
            JFormattedTextField campoNovoCEP = new JFormattedTextField(maskCEP);

            Cliente c = (Cliente) cliente;

            // Preenche o campo com o CEP atual
            campoNovoCEP.setValue(c.getCep());

            // Exibe o dialog
            int opcao = JOptionPane.showConfirmDialog(
                this,
                campoNovoCEP,
                "Digite o novo CEP:",
                JOptionPane.OK_CANCEL_OPTION,
                JOptionPane.PLAIN_MESSAGE
            );

            // Se o usuário clicou em OK
            if (opcao == JOptionPane.OK_OPTION) {
                String novoCep = campoNovoCEP.getText();

                if (novoCep.contains("_") || novoCep.length() < 9) {
                    JOptionPane.showMessageDialog(this, "CEP incompleto.");
                } else {
                    c.setCep(novoCep);
                    campoCEP.setText(novoCep); // aqui é o campo real da tela
                }
            }
        } catch (ParseException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Erro ao formatar o campo CEP.");
        }
    }//GEN-LAST:event_botaoEditarEmailActionPerformed

    private void botaoEditarCEPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoEditarCEPActionPerformed
        String novoNome = JOptionPane.showInputDialog(this, "Digite o novo nome:", cliente.getNome());
        if (novoNome != null && !novoNome.trim().isEmpty()) {
            cliente.setNome(novoNome);
            labelNomeValor.setText(novoNome);
        }
    }//GEN-LAST:event_botaoEditarCEPActionPerformed

    private void botaoEditarNumResidenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoEditarNumResidenciaActionPerformed
        Cliente c = (Cliente) cliente;
        
        String novoNumero = JOptionPane.showInputDialog(this, "Digite o novo número da residência:", c.getNumero());
        if (novoNumero != null && !novoNumero.trim().isEmpty()) {
            c.setNumero(novoNumero);
            campoNumResidencia.setText(novoNumero);
        }
    }//GEN-LAST:event_botaoEditarNumResidenciaActionPerformed

    private void botaoEditarTelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoEditarTelefoneActionPerformed
        String novoEmail = JOptionPane.showInputDialog(this, "Digite o novo email:", cliente.getEmail());
        if (novoEmail != null && !novoEmail.trim().isEmpty()) {
            cliente.setEmail(novoEmail);
            campoEmail.setText(novoEmail);
        }
    }//GEN-LAST:event_botaoEditarTelefoneActionPerformed

    /**
     * @param args the command line arguments
     */
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoEditarCEP;
    private javax.swing.JButton botaoEditarEmail;
    private javax.swing.JButton botaoEditarNome;
    private javax.swing.JButton botaoEditarNumResidencia;
    private javax.swing.JButton botaoEditarTelefone;
    private javax.swing.JLabel campoCEP;
    private javax.swing.JLabel campoEmail;
    private javax.swing.JLabel campoNumResidencia;
    private javax.swing.JLabel campoTelefone1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel labelCEP;
    private javax.swing.JLabel labelEmail;
    private javax.swing.JLabel labelEmail1;
    private javax.swing.JLabel labelNomeValor;
    private javax.swing.JLabel labelNumResidencia;
    private javax.swing.JLabel labelTelefone;
    private javax.swing.JLabel labelTelefone1;
    private javax.swing.JLabel labelUsuarioLogado;
    // End of variables declaration//GEN-END:variables
}
