/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ViewLuidgi;
import ModelLuidgi.Cliente;
import ModelLuidgi.Usuario;
import ModelLuidgi.Entregador;
import ModelLuidgi.UsuarioLogado;
import ModelLuidgi.SessaoUsuario;
import javax.swing.JOptionPane;
import javax.swing.text.MaskFormatter;
import javax.swing.JFormattedTextField;
import java.text.ParseException;
import java.awt.Font;
import java.awt.Window;
import javax.swing.SwingUtilities;
/**
 *
 * @author luidgivarela
 */
public class ConsultaPerfilEntregador extends javax.swing.JFrame implements UsuarioLogado{

    private Entregador entregador;

    public ConsultaPerfilEntregador(Entregador entregador) {
        this.entregador = entregador;        
        initComponents(); 
        setUsuarioLogado(entregador); 
        setSize(900, 800);
        setLocationRelativeTo(null);
    }

    @Override
    public void setUsuarioLogado(Usuario usuario) {
        this.entregador = (Entregador) usuario;
        String nomeCompleto = entregador.getNome();
        String nomeCurto = nomeCompleto.length() > 18 ? nomeCompleto.substring(0, 18) + "..." : nomeCompleto;

        labelUsuarioLogado.setText("Entregador: " + nomeCurto);
        labelUsuarioLogado.setToolTipText("Entregador: " + nomeCompleto);
        preencherDados();
    }

    @Override
    public Usuario getUsuarioLogado() {
        return this.entregador;
    }

    private void preencherDados() {
        campoNome.setText(entregador.getNome());
        campoTelefone.setText(entregador.getTelefone());
        campoEmail.setText(entregador.getEmail());

        campoNome.setEnabled(false);
        campoTelefone.setEnabled(false);
        campoEmail.setEnabled(false);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        labelUsuarioLogado = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jButton8 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        labelTelefone1 = new javax.swing.JLabel();
        labelEmail1 = new javax.swing.JLabel();
        campoNome = new javax.swing.JLabel();
        campoTelefone = new javax.swing.JLabel();
        campoEmail = new javax.swing.JLabel();
        botaoEditarNome = new javax.swing.JButton();
        botaoEditarTelefone = new javax.swing.JButton();
        botaoEditarCEP = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(123, 63, 0));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jButton1.setBackground(new java.awt.Color(255, 193, 7));
        jButton1.setText("🍕 Início");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(255, 193, 7));
        jButton3.setText("👋 Sair");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(255, 193, 7));
        jButton6.setText("👤Consulte seu Perfil");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        labelUsuarioLogado.setBackground(new java.awt.Color(255, 193, 7));
        labelUsuarioLogado.setText("Usuário:");
        labelUsuarioLogado.setOpaque(true);
        labelUsuarioLogado.setPreferredSize(new java.awt.Dimension(156, 23));

        jButton2.setBackground(new java.awt.Color(255, 0, 0));
        jButton2.setText("Logout");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelUsuarioLogado, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addGap(18, 18, 18)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton3)
                    .addComponent(jButton6)
                    .addComponent(labelUsuarioLogado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addContainerGap(11, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 248, 220));

        jLabel1.setFont(new java.awt.Font("Herculanum", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Dados do seu perfil");

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jButton8.setBackground(new java.awt.Color(255, 193, 7));
        jButton8.setText("✅Salvar aterações");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jLabel2.setText("👤Seu nome:");

        labelTelefone1.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        labelTelefone1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTelefone1.setText("📞 Seu telefone:");

        labelEmail1.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        labelEmail1.setText("📧 Seu email:");

        campoNome.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(123, 63, 0), 3));

        campoTelefone.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(123, 63, 0), 3));

        campoEmail.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(123, 63, 0), 3));

        botaoEditarNome.setBackground(new java.awt.Color(255, 193, 7));
        botaoEditarNome.setText("🛠️ Editar");
        botaoEditarNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoEditarNomeActionPerformed(evt);
            }
        });

        botaoEditarTelefone.setBackground(new java.awt.Color(255, 193, 7));
        botaoEditarTelefone.setText("🛠️ Editar");
        botaoEditarTelefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoEditarTelefoneActionPerformed(evt);
            }
        });

        botaoEditarCEP.setBackground(new java.awt.Color(255, 193, 7));
        botaoEditarCEP.setText("🛠️ Editar");
        botaoEditarCEP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoEditarCEPActionPerformed(evt);
            }
        });

        jButton9.setBackground(new java.awt.Color(255, 193, 7));
        jButton9.setText("✅Salvar aterações");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton9)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addGap(353, 353, 353)
                            .addComponent(jLabel2)
                            .addGap(18, 18, 18)
                            .addComponent(campoNome, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(12, 12, 12)
                            .addComponent(botaoEditarCEP))
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addGap(321, 321, 321)
                            .addComponent(labelTelefone1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(19, 19, 19)
                            .addComponent(campoTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(12, 12, 12)
                            .addComponent(botaoEditarNome))
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addGap(341, 341, 341)
                            .addComponent(labelEmail1)
                            .addGap(19, 19, 19)
                            .addComponent(campoEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(12, 12, 12)
                            .addComponent(botaoEditarTelefone))
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addGap(785, 785, 785)
                            .addComponent(jButton8))))
                .addGap(167, 167, 167))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel2))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(campoNome, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(botaoEditarCEP))
                .addGap(14, 14, 14)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botaoEditarNome, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelTelefone1)
                            .addComponent(campoTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelEmail1)
                    .addComponent(campoEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoEditarTelefone))
                .addGap(68, 68, 68)
                .addComponent(jButton9)
                .addGap(49, 49, 49)
                .addComponent(jButton8))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(457, 457, 457)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(393, 393, 393))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(350, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        LoginCliente_back telaLogin = new LoginCliente_back();
        telaLogin.setVisible(true);
        this.dispose(); // Fecha a tela atual
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
Usuario usuarioLogado = SessaoUsuario.getInstancia().getUsuarioLogado();

    if (usuarioLogado == null) {
        JOptionPane.showMessageDialog(this, "Usuário não está logado.");
        return;
    }

    if (usuarioLogado instanceof Entregador) {
        Entregador entregadorLogado = (Entregador) usuarioLogado;
        ConsultaPerfilEntregador telaPerfil = new ConsultaPerfilEntregador(entregadorLogado);
        telaPerfil.setVisible(true);
        this.dispose();
    } else if (usuarioLogado instanceof Cliente) {
        Cliente clienteLogado = (Cliente) usuarioLogado;
        ConsultaPerfilCliente_back telaPerfilCliente = new ConsultaPerfilCliente_back(clienteLogado);
        telaPerfilCliente.setVisible(true);
        this.dispose();
    } else {
        JOptionPane.showMessageDialog(this, "Tipo de usuário não reconhecido.");
    }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        JOptionPane.showMessageDialog(this, "✔️ Alterações registradas!");
    }//GEN-LAST:event_jButton8ActionPerformed

    private void botaoEditarNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoEditarNomeActionPerformed
        try {
            // Máscara para telefone: (##) #####-####
            MaskFormatter formatter = new MaskFormatter("(##) #####-####");
            formatter.setPlaceholderCharacter('_');

            // Campo formatado usado apenas no JOptionPane
            JFormattedTextField campoNovoTelefone = new JFormattedTextField(formatter);
            campoNovoTelefone.setValue(entregador.getTelefone());
            campoNovoTelefone.setFont(new Font("SansSerif", Font.PLAIN, 14));
            campoNovoTelefone.setColumns(14);

            int opcao = JOptionPane.showConfirmDialog(
                this,
                campoNovoTelefone,
                "Digite o novo telefone:",
                JOptionPane.OK_CANCEL_OPTION,
                JOptionPane.PLAIN_MESSAGE
            );

            if (opcao == JOptionPane.OK_OPTION) {
                String novoTelefone = campoNovoTelefone.getText();

                if (novoTelefone != null && !novoTelefone.contains("_") && !novoTelefone.trim().isEmpty()) {
                    entregador.setTelefone(novoTelefone); // atualiza o objeto
                    campoTelefone.setText(novoTelefone);  // atualiza o campo visível
                } else {
                    JOptionPane.showMessageDialog(this, "Telefone incompleto.");
                }
            }
        } catch (ParseException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Erro ao formatar o telefone.");
        }
    }//GEN-LAST:event_botaoEditarNomeActionPerformed

    private void botaoEditarTelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoEditarTelefoneActionPerformed
        String novoEmail = JOptionPane.showInputDialog(this, "Digite o novo email:", entregador.getEmail());
        if (novoEmail != null && !novoEmail.trim().isEmpty()) {
            entregador.setEmail(novoEmail);
            campoEmail.setText(novoEmail);
        }      
    }//GEN-LAST:event_botaoEditarTelefoneActionPerformed

    private void botaoEditarCEPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoEditarCEPActionPerformed
        String novoNome = JOptionPane.showInputDialog(this, "Digite o novo nome:", entregador.getNome());
        if (novoNome != null && !novoNome.trim().isEmpty()) {
            entregador.setNome(novoNome);
            campoNome.setText(novoNome);
        }      
        
    }//GEN-LAST:event_botaoEditarCEPActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
 JOptionPane.showMessageDialog(this, "✔ Alterações registradas!");

    SessaoUsuario.getInstancia().setUsuarioLogado(entregador); // ← força o refresh da sessão

    Entregador entregadorLogado = (Entregador) SessaoUsuario.getInstancia().getUsuarioLogado();
    ConsultaPerfilEntregador novaTela = new ConsultaPerfilEntregador(entregadorLogado);
    novaTela.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // 1. Pega o usuário antes de limpar a sessão
        Usuario usuario = SessaoUsuario.getInstancia().getUsuarioLogado();

        // 2. Limpa a sessão
        SessaoUsuario.getInstancia().setUsuarioLogado(null);

        // 3. Reabre a tela de login correspondente
        if (usuario instanceof Cliente) {
            new LoginCliente_back().setVisible(true);
        } else if (usuario instanceof Entregador) {
            new LoginEntregador().setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "Tipo de usuário desconhecido.");
            return;
        }

        // 4. Fecha a janela atual
        Window janelaAtual = SwingUtilities.getWindowAncestor(jButton2);
        if (janelaAtual != null) {
            janelaAtual.dispose();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    //public static void main(String args[]) {
    //    java.awt.EventQueue.invokeLater(() -> {
    //    Entregador entregadorTeste = new Entregador(
    //        "João Entregador", "joao@teste.com", "senha123", "99999-9999", "123.456.789-00", "CNH123"
    //    );
    //    new ConsultaPerfilEntregador(entregadorTeste).setVisible(true);
    //});
    //}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoEditarCEP;
    private javax.swing.JButton botaoEditarNome;
    private javax.swing.JButton botaoEditarTelefone;
    private javax.swing.JLabel campoEmail;
    private javax.swing.JLabel campoNome;
    private javax.swing.JLabel campoTelefone;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel labelEmail1;
    private javax.swing.JLabel labelTelefone1;
    private javax.swing.JLabel labelUsuarioLogado;
    // End of variables declaration//GEN-END:variables
}
